language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rhgrant10
  password:
    secure: RqlkMTktF7hHUodl2tAHaRGyM39V+lS2cc3AWoYAWwU8zvjRz8prmlKsnxn052VR4AyshgKce3RMSPkc7j7flUgUzL2bHofgpqUb6bk99cBvJgwsw+d0XeWc0h/iSSXKy+PEvyOhHSwR11HSKDuvDT1pPpReFasLOuHQoexHtHo=
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = 3.6
